mecoL1:
  et_dir: "./meco-features/"
  et_orig: "."
  meco_webcam_dir: "./webcam_meco/"
  results_dir: "./results/"
  languages: ["en", "tr", "ru", "gr", "ge", "sp"]
  languages_web: ["en"] #"en", "de", "es", "tr", "ru", "gr"
